logging:
  level:
    org.apache.http: INFO
#    org.neo4j.ogm.drivers.bolt.request: WARN
spring:
  data:
    neo4j:
      username: neo4j
      password: 123
      uri: bolt://localhost:7687
      embedded:
        enabled: false

#      repositories:
#        enabled: true

config:
  dataDir: data
  nalog:
    enbled: false
    url: url
    p12: pathP12Container
    password: passwordConteiner
    autification: autorization basic user:password
