logging:
  level:
    org.apache.http: info
    org.hibernate: info
    org.hibernate.stat: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.hql.ast.AST: info
    org.hibernate.tool.hbm2ddl: warn
    org.hibernate.hql: debug
    org.hibernate.cache: info
    org.hibernate.jdbc: debug

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 500
#        jdbc.batch_versioned_data: true
        cache.use_second_level_cache: false
        generate_statistics: true