logging:
  level:
    org.apache.http: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/egrul?useSSL=false
    username: root
    password: qaz1234
  jpa:
    hibernate:
      ddl-auto: create
  cache:
    cache-names:
       - NaturalPerson
       - EconomicActivity
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=600s
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml

config:
  dataDir: data
  nalog:
    enbled: false
    url: url
    p12: pathP12Container
    password: passwordConteiner
    autification: autorization basic user:password
