logging:
  level:
    org.apache.http: info
    org.hibernate: info
#    org.hibernate.stat: debug
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    org.hibernate.hql.ast.AST: info
#    org.hibernate.tool.hbm2ddl: warn
#    org.hibernate.hql: debug
#    org.hibernate.cache: info
#    org.hibernate.jdbc: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/egrul?useSSL=false
    username: root
    password: qaz1234
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
        use_sql_comments: true
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 500
#        jdbc.batch_versioned_data: true
        cache.use_second_level_cache: false
#        generate_statistics: true
  cache:
    cache-names:
       - NaturalPerson
       - EconomicActivity
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=600s
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
##Apender
config:
  dataDir: data
  nalog:
    enbled: false
    url: url
    p12: pathP12Container
    password: passwordConteiner
    autification: autorization basic user:password
